import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import logo from "../public/logo.svg";


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
   <main>
     <section>
       <nav>
         <div>
           <Link>
              <Image src={logo} alt="logo" quality={100}/>
           </Link>
           <ul>
             <li>
             <Link>
              <Image src={bgLogo} alt="fb" quality={100}/>
           </Link>
             </li>
             <li>
             <Link>
              <Image src={igLogo} alt="ig" quality={100}/>
           </Link>
             </li>
             <li>
             <Link>
              <Image src={ytLogo} alt="yt" quality={100}/>
           </Link>
             </li>
           </ul>
         </div>
       </nav>
     </section>
   </main>
    </>
  )
}
