import Head from 'next/head'

import { HeroComponent } from '@/components/HeroComponent';
import { GalleryMain } from '@/components/GalleryMain';
import { ContactMain } from '@/components/ContactMain';


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <HeroComponent/>
      <GalleryMain/>
      <ContactMain/>
      </main>
    </>
  )
}
